
version: '3.1'
services :
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vote_system
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
